version: '3.8'

services:
  ml-api:
    build: .
    container_name: diabetic-readmission-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./models:/app/models:ro
      - ./feature_scaler.pkl:/app/feature_scaler.pkl:ro
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ml-network

  # Optional: Add monitoring service
  monitoring:
    image: prom/prometheus:latest
    container_name: ml-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge

volumes:
  logs:
    driver: local
