[build]
builder = "nixpacks"

[deploy]
startCommand = "cd notebooks && python app_improved.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.regions]
"us-west" = 1
