version: '3.8'

services:
  ml-pipeline:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
      - MODEL_PATH=/app/models
    restart: unless-stopped

  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/app/mlflow
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
    command: mlflow ui --host 0.0.0.0 --port 5000
    restart: unless-stopped
